### ISSUE TITLE
Make this work in node

### ISSUE THREAD

**Issue by udaraweerasinghege** [wealthsimple/wealthsimple.js#36]
Currently this only works on the frontend as it looks for a window object
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/nsaravanan/Desktop/Projects/WealthSimplePlaceHolder/node_modules/@wealthsimple/wealthsimple/dist/wealthsimple.min.js:1:268)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nsaravanan/Desktop/Projects/WealthSimplePlaceHolder/server.js:1:84)
    at Module._compile
```
setting global.window = {} before requiring the package is the hack we used in the hackathon

**Comment by malcolmocean** [comment]
I had this same issue with an install I just did `ReferenceError: window is not defined` (same segment of code: `wealthsimple.min.js:1:268`)

(Also I have to require it with `require('@wealthsimple/wealthsimple')` since it isn't in npm yet.
